create table if not exists customers (
 id bigint generated by default as identity primary key,
 name text not null, phone text, zalo text, address text, source text default 'Khác', stage text default 'Khách mới', need text, budget numeric default 0, note text,
 created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists activities (
 id bigint generated by default as identity primary key,
 customer_id bigint not null references customers(id) on delete cascade,
 type text, title text not null, content text, created_at timestamptz default now()
);
create table if not exists tasks (
 id bigint generated by default as identity primary key,
 customer_id bigint references customers(id) on delete cascade,
 title text not null, due_date timestamptz not null, priority text default 'Bình thường', completed boolean default false, note text
);
create table if not exists appointments (
 id bigint generated by default as identity primary key,
 customer_id bigint references customers(id) on delete cascade,
 title text not null, starts_at timestamptz not null, duration_minutes integer default 60, location text, note text, completed boolean default false
);

create table if not exists projects (
 id bigint generated by default as identity primary key,
 customer_id bigint not null references customers(id) on delete cascade,
 name text not null, address text, category text, aluminum_system text, accessory text,
 status text default 'Chuẩn bị', start_date timestamptz, install_date timestamptz, note text,
 created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists quotes (
 id bigint generated by default as identity primary key,
 customer_id bigint not null references customers(id) on delete cascade,
 project_id bigint references projects(id) on delete set null,
 code text not null, amount numeric default 0, status text default 'Nháp',
 valid_until timestamptz, note text, created_at timestamptz default now()
);
create table if not exists contracts (
 id bigint generated by default as identity primary key,
 customer_id bigint not null references customers(id) on delete cascade,
 project_id bigint references projects(id) on delete set null,
 code text not null, value numeric default 0, signed_at timestamptz, install_date timestamptz,
 warranty_months integer default 12, status text default 'Đã ký', note text,
 created_at timestamptz default now()
);
create table if not exists payments (
 id bigint generated by default as identity primary key,
 contract_id bigint not null references contracts(id) on delete cascade,
 customer_id bigint not null references customers(id) on delete cascade,
 amount numeric default 0, paid_at timestamptz default now(), method text, note text
);

create index if not exists idx_projects_customer on projects(customer_id);
create index if not exists idx_quotes_customer on quotes(customer_id);
create index if not exists idx_contracts_customer on contracts(customer_id);
create index if not exists idx_payments_contract on payments(contract_id);
