create table if not exists customers (
 id bigint generated by default as identity primary key,
 name text not null, phone text, zalo text, address text, source text default 'Khác', stage text default 'Khách mới', need text, budget numeric default 0, note text,
 created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists activities (
 id bigint generated by default as identity primary key,
 customer_id bigint not null references customers(id) on delete cascade,
 type text, title text not null, content text, created_at timestamptz default now()
);
create table if not exists tasks (
 id bigint generated by default as identity primary key,
 customer_id bigint references customers(id) on delete cascade,
 title text not null, due_date timestamptz not null, priority text default 'Bình thường', completed boolean default false, note text
);
create table if not exists appointments (
 id bigint generated by default as identity primary key,
 customer_id bigint references customers(id) on delete cascade,
 title text not null, starts_at timestamptz not null, duration_minutes integer default 60, location text, note text, completed boolean default false
);
